### ISSUE TITLE
Request: add own  domain names

### ISSUE THREAD

**Issue by Thomas--F** [aaronsaray/feedlybackgroundtab#21]
Hi,

the extension is really useful, but I have my own RSS-Feed-Server based on selfoss (https://github.com/SSilence/selfoss )
There is a similar hotkey "v" to open a current feed-link in a new tab but I want do open it in the background. Maybe it will work if I can simply add my local domain (e.g. "selfoss.local") to the extensions domain-list.

**Comment by bbbrrriiiaaannn** [comment]
This extension is necessarily tailored pretty specifically to Feedly—it depends on Feedly's markup structure to find the currently selected item, and its `manifest.json` URL permissions (which tell Chrome on what URLs to let the extension run) are targeted to Feedly URLs (rather than on any page).

If you're up to it, forking this and building a version customized to your Selfoss install should be pretty straightforward!

1. Clone the repo locally
2. Update [this block](https://github.com/aaronsaray/feedlybackgroundtab/blob/8010f73a0e1a8635eebd0556e478db423339a665/src/manifest.json#L14-L17) in `manifest.json` to point to your Selfoss' URL
3. Update [this block](https://github.com/aaronsaray/feedlybackgroundtab/blob/8010f73a0e1a8635eebd0556e478db423339a665/src/js/keypress.js#L12-L16) in `keypress.js` with a CSS selector that targets an entry that's been highlighted by keyboard browsing in Selfoss (looking at the [Selfoss source](https://github.com/SSilence/selfoss/blob/3fb536648735c55b0f507d079ab6cba32e3cbb34/public/js/selfoss-shortcuts.js#L272) it looks like that would be `'.entry.selected'`, but I don't have an install going to confirm that)
4. Use ['Load Unpacked'](https://developer.chrome.com/extensions/getstarted#manifest) on Chrome's Extensions page to run your personal version

Hope this inspires!
