### ISSUE TITLE
Doesn't always work

### ISSUE THREAD

**Issue by j4h4x** [aaronsaray/feedlybackgroundtab#7]
0.6 doesn't always work. Sometimes it recognizes the shortcut key and a new tab is opened, but quite often not.

**Comment by coke** [comment]
It's been fine for a while, but I am seeing the error right now, looking at xkcd's latest "what if".

If I check the chrome console, I see:

10101_web03.js:1274 Uncaught TypeError: Cannot read property 'getDOMNode' of undefined

which I don't expect is your code, even.

**Comment by coke** [comment]
Issue is persisting after a browser reload, is now on a different entry, and there are no errors on the console at all.

**Comment by aaronsaray** [comment]
Would you be willing to run with a development version of the extension if I packaged one up and put it in a branch for you?  I'm would probably add a bunch more logging in the console so that maybe we could track this down.  If you're willing to do this, it'll be a xpi you'll have to download and install - but I'll give more instructions.  If not, no big dealio.  Just gonna have to run it only myself then.

**Comment by coke** [comment]
Sure; I can do a build off a github branch if that would work, also.

**Comment by aaronsaray** [comment]
@coke I put console logging in the logging branch - I've installed from the src folder - can you do the same and let me know what you see when it fails next?  thanks!

**Comment by coke** [comment]
Ok. From home page, card view, click on first item. You get one of the (newish) tabs to pop over the content. from there, hitting ";" does nothing, and you get this logging:

```
Tag: body
keypress.js:54 Could not find .selectedEntry a.title
```

**Comment by coke** [comment]
Expand left sidebar. Pick one of your groups of feeds (that presents as title bar), it opens up on the right hand side, main content area.

Click on the first item. It expands. ";" does nothing, you get the same logging as above.

```
Tag: body
keypress.js:54 Could not find .selectedEntry a.title
```
If you press j, then k, then ;, then it works.

**Comment by aaronsaray** [comment]
Pushed new update 0.7 out.  Should update shortly.  Please let me know if this works for you - I found that it works in the scenarios you stated (at least for me!)

**Comment by woodspock** [comment]
With update 0.7,  same link always opens in background. Precisely, it's the first one of the selected feedly folder which is opened.

**Comment by politicus** [comment]
Not working for me. Reinstalled the latest version (0.7) from Github. 
Still not working. 

Google Chrome v43.0.2357.81 (2357.81)

**Comment by aaronsaray** [comment]
@politicus Do you see any errors in the console?   What exact view are you using?  Can you describe the process in which you're browsing - and what you're doing that is not working as expected?  I use it every day myself - so I'm obviously using it a different way - because I'm not seeing the issue.

Sorry for the delay in response by the way!
